[global]
keyboard = "it-it"
country = "it"
fqdn = "pveauto.testinstall"
mailto = "mail@no.invalid"
timezone = "Europe/Rome"
root_password = "123456"
root_ssh_keys = []

[network]
source = "from-dhcp"

[disk-setup]
filesystem = "zfs"
zfs.raid = "raid1"
zfs.ashift = 12
zfs.checksum = "on"
zfs.compress = "lz4"
zfs.copies = 2
zfs.hdsize = 95
disk_list = ["sda", "sdb"]

[custom]
github_username = "grimmo" # Will add this user's GitHub public key(s) to global.root_ssh_keys[].
