[global]
keyboard = "it"
country = "it"
fqdn = "pveauto.testinstall"
mailto = "mail@no.invalid"
timezone = "Europe/Rome"
root_password = "123456"
root_ssh_keys = ["ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFUfZmhS0G1bMRpjLS54eeUTu9Fo+q1VIRGlT45LKpA0 gigi@proxmox"]

[network]
source = "from-dhcp"

[disk-setup]
filesystem = "zfs"
zfs.raid = "raid1"
disk_list = ["sda", "sdb"]
