[global]
keyboard = "it-it"
country = "it"
fqdn = "pveauto.testinstall"
mailto = "mail@no.invalid"
timezone = "Europe/Rome"
root_password = "123456"
root_ssh_keys = []

[network]
source = "from-dhcp"

[disk-setup]
filesystem = "ext4"

[custom]
github_username = "grimmo" # Will add this user's GitHub public key(s) to global.root_ssh_keys[].
